### ISSUE TITLE
Plugin breaks when applied to a file containing a css property set

### ISSUE THREAD

**Issue by dantman** [jonathantneal/postcss-pseudo-class-any-link#4]
The [@apply spec](https://tabatkins.github.io/specs/css-apply-rule/) defines 'css property sets' like this:

``` css
.warning {
  --toolbar-title-theme: {
    color: red;
    font-weight: bold;
  };
}
```

These are currently in production use on sites using Polymer.

However when trying to process css with this plugin I get an error like:

```
Error: Expected pseudo-class or pseudo-element
    at new error ({app}/node_modules/postcss-selector-parser/dist/processor.js:27:23)
    at Parser.error ({app}/node_modules/postcss-selector-parser/dist/parser.js:212:15)
    at Parser.pseudo ({app}/node_modules/postcss-selector-parser/dist/parser.js:292:25)
    at Parser.parse ({app}/node_modules/postcss-selector-parser/dist/parser.js:502:22)
    at Parser.loop ({app}/node_modules/postcss-selector-parser/dist/parser.js:470:18)
    at new Parser ({app}/node_modules/postcss-selector-parser/dist/parser.js:89:21)
    at Processor.process ({app}/node_modules/postcss-selector-parser/dist/processor.js:24:21)
    at {app}/node_modules/postcss-pseudo-class-any-link/index.js:48:7
    at {app}/node_modules/postcss/lib/container.js:118:28
    at {app}/node_modules/postcss/lib/container.js:81:26
    at Rule.each ({app}/node_modules/postcss/lib/container.js:68:22)
    at Rule.walk ({app}/node_modules/postcss/lib/container.js:80:21)
    at {app}/node_modules/postcss/lib/container.js:83:32
    at Root.each ({app}/node_modules/postcss/lib/container.js:68:22)
    at Root.walk ({app}/node_modules/postcss/lib/container.js:80:21)
    at Root.walkRules ({app}/node_modules/postcss/lib/container.js:116:25)
```

This bug is exclusive to any-link. I have postcss-selector-matches, postcss-selector-not, and postcss-nesting all present and none of them have an issue with the syntax.

**Comment by texastoland** [comment]
This is coming from the new postcss/postcss-selector-parser#28 dependency.

**Comment by texastoland** [comment]
Relevant issues:
https://github.com/Microsoft/TypeScript/issues/6508#issuecomment-224428750
https://github.com/Microsoft/TypeScript/issues/9017
